language:
  - java
java:
  - "1.8"
jdk:
  - oraclejdk8
branches:
  only:
    - master
sudo: required
install: mvn clean install
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
